spring:
    profiles:
     active: dev
     #active: test

---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    #メモリDB
    #url: jdbc:h2:file:~/hajibootdb;AUTO_SERVER=true
    #ファイルDB
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: 
  jpa:
    hibernate.ddl-auto: validate #変更を保管
    #hibernate.ddl-auto: create-drop #毎回リフレッシュ
---
spring:
    profiles: test
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/shopping
      username: johndoe
      password: johndoe
      xa:
        dataSourceClassName: org.postgresql.xa.PGXADataSource

    #hibernate.ddl-auto: create-drop #毎回リフレッシュ

