spring:
    profiles:
     active: dev
     #active: test

---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    #メモリDB
    #url: jdbc:h2:file:~/hajibootdb;MODE=PostgreSQL;AUTO_SERVER=true
    #ファイルDB
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sapppp
    password: 
  jpa:
    #hibernate.ddl-auto: validate #変更を保管
    hibernate.ddl-auto: create-drop #毎回リフレッシュ　　
    
---
spring:
    profiles: test
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/meeting4
      username: johndoe
      password: johndoe
      xa:
        dataSourceClassName: org.postgresql.xa.PGXADataSource
    #hibernate.ddl-auto: validate #変更を保管
    jpa:
    #You can set spring.jpa.hibernate.ddl-auto explicitly and the standard Hibernate property values are none, validate, update, create, create-drop.
      hibernate.ddl-auto: ddl-auto #毎回DBをリフレッシュ（これをセットするとdata.sqlが読み込まれるようになる


